### ISSUE TITLE
Which config files did you use to get the paper's score?

### ISSUE THREAD

**Issue by kawa-work** [tsinghua-fib-lab/PIML#1]
Hello, I'm Kawakami.
Thank you for the great repository.

I would like to reproduce the score in the paper. 
Could you please tell me the config file you used?

Thank you in advance.

Kawakami

**Comment by EricGz** [comment]
The configs have been updated.

**Comment by xingchenfys** [comment]
hello!
Do you know how the  synthetic data was obtained?

**Comment by xingchenfys** [comment]
hello!
Do you know how the  synthetic data was obtained?

**Comment by xingchenfys** [comment]
hello!
Do you know how the  synthetic data was obtained?
